import Papa from 'papaparse';
export async function readFile(file){
 if(file.size>15*1024*1024)throw Error('Maximum file size is 15 MB.');
 if(/\.csv$/i.test(file.name)){const parsed=Papa.parse(await file.text(),{skipEmptyLines:'greedy'});if(parsed.errors.length)throw Error('CSV could not be read: '+parsed.errors[0].message);return parsed.data;}
 if(!/\.xlsx$/i.test(file.name))throw Error('Upload a .csv or .xlsx file. Save older .xls files as .xlsx first.');
 const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const ws=wb.worksheets[0];if(!ws)throw Error('No worksheet found.');if(ws.rowCount>50001)throw Error('Use a maximum of 50,000 data rows.');
 const rows=[];ws.eachRow({includeEmpty:true},r=>{const values=[];for(let i=1;i<=Math.max(ws.columnCount,6);i++){const c=r.getCell(i);if(c.type===ExcelJS.ValueType.Formula&&c.result===undefined)throw Error('Save formula results in Excel before uploading.');values.push(c.value instanceof Date?c.value.toISOString().slice(0,10):c.text);}rows.push(values);});return rows;
}
export async function exportReport(details,items){const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();wb.creator='TEAME';for(const [name,rows] of [['Product detail',details],['Item totals',items]]){const ws=wb.addWorksheet(name);const headers=Object.keys(rows[0]);ws.columns=headers.map(h=>({header:h,key:h,width:Math.max(19,h.length+3)}));rows.forEach(r=>ws.addRow(r));ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF174E42'}};ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:'A1',to:{row:1,column:headers.length}};}
 const notes=wb.addWorksheet('Read me');notes.addRows([['Projection rule','Gross Units × 1.25, rounded up to whole units'],['Period','Entire uploaded sales period. No monthly or seasonal normalization.'],['Grouping','Product detail: Item ID + Product Id + SKU ID'],['Item totals','Sum Gross Units by Item ID, then apply 25% and round up.'],['Rounding','Item totals can differ from summed detail projections due to rounding.'],['Cancellation units','Retained in source data; not subtracted from Gross Units.'],['Created',new Date().toISOString()]]);notes.columns=[{width:24},{width:95}];
 const blob=new Blob([await wb.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='TEAME-item-projection.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
