import './style.css';
import {validateRows,project,itemTotals} from './core.js';
import {readFile,exportReport} from './files.js';
import {cloud,saveWorkspace,loadWorkspace} from './cloud.js';
let sales=[],master=[],salesName='',masterName='',user=null,busy=false,tab='detail',search='',page=0;
const $=id=>document.getElementById(id);const num=n=>n.toLocaleString('en-IN');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelector('#app').innerHTML=`
<header><a class="brand" href="/">TEAME<span>Planning workspace</span></a><span class="status" id="connection">Session only</span></header>
<main><div class="title"><div><h1>Sales projection</h1><p>Previous sales. Clearer purchase planning.</p></div><button class="primary" id="download" disabled>Download projected report <span aria-hidden="true">↓</span></button></div>
<section class="formula"><div><strong>A little room to grow.</strong><p>Your gross sales, with a 25% planning buffer.</p></div><div class="equation">Gross units <b>× 1.25</b><span>Rounded up to whole units</span></div></section>
<section class="uploads" aria-label="Upload your data"><article><div class="step">1 <h2>Item master</h2></div><p>Connect your internal Item IDs to Product IDs.</p><label class="drop" for="master"><strong id="masterName">Choose item master</strong><span>Excel (.xlsx) or CSV · up to 15 MB</span><input id="master" type="file" accept=".csv,.xlsx"></label><div class="upload-foot"><span id="masterCount">No mappings yet</span><a href="/templates/item-master-template.csv" download>Download template</a></div><small>Required: Item ID, Product Id</small></article>
<article><div class="step">2 <h2>Previous sales</h2></div><p>Upload the sales period you want to project from.</p><label class="drop" for="sales"><strong id="salesName">Choose sales report</strong><span>Excel (.xlsx) or CSV · up to 15 MB</span><input id="sales" type="file" accept=".csv,.xlsx"></label><div class="upload-foot"><span id="salesCount">No sales uploaded</span><a href="/templates/sales-template.csv" download>Download template</a></div><small>Product Id, Order Date, SKU ID, Gross Units, Cancellation Units, Final Sale Units</small></article></section>
<div class="message" id="message" role="status" aria-live="polite" hidden></div>
<section class="results"><div class="result-head"><div><h2>Your projection</h2><p id="summary">Upload both files to build your item-wise report.</p></div><label class="search">Find an item<input id="search" placeholder="Item, product or SKU" type="search"></label></div><div class="table-tools"><div class="tabs" role="group" aria-label="Report view"><button id="detail" class="selected" aria-pressed="true">Product detail</button><button id="items" aria-pressed="false">Item totals</button></div><span id="rowCount">0 rows</span></div><div class="table-wrap" id="table"></div><div class="pagination"><span id="pageInfo"></span><div><button id="prev" disabled>Previous</button><button id="next" disabled>Next</button></div></div></section>
<section class="cloud"><div><h2>Keep your workspace</h2><p id="cloudText">Files stay in this session until you connect Supabase. Download your report before closing.</p></div><div id="auth"></div></section>
<footer>Projection uses the entire uploaded period. A new upload replaces the current file.<br>Cancellation and Final Sale Units do not change the Gross Units calculation.</footer></main>`;
function message(text,error=false){$('message').hidden=!text;$('message').textContent=text;$('message').className='message'+(error?' error':'');}
async function action(fn){if(busy)return;busy=true;document.body.classList.add('busy');document.querySelectorAll('input[type=file]').forEach(e=>e.disabled=true);try{await fn();}catch(e){message(e.message||'Something went wrong. Please try again.',true);}finally{busy=false;document.body.classList.remove('busy');document.querySelectorAll('input[type=file]').forEach(e=>e.disabled=false);render();}}
function render(){const rows=project(sales,master),items=itemTotals(rows),unmatched=rows.filter(r=>!r['Item ID']);const missing=[...new Set(unmatched.map(r=>r['Product Id']))];$('masterName').textContent=masterName||'Choose item master';$('salesName').textContent=salesName||'Choose sales report';$('masterCount').textContent=master.length?num(master.length)+' product mappings':'No mappings yet';$('salesCount').textContent=sales.length?num(sales.length)+' sales rows':'No sales uploaded';$('download').disabled=busy||!rows.length||!!missing.length;
 $('summary').textContent=rows.length?`${num(rows.reduce((n,r)=>n+r['Gross Units(total)'],0))} gross units · ${num(items.reduce((n,r)=>n+r['Projected unit'],0))} projected units across ${num(items.length)} mapped items`:'Upload both files to build your item-wise report.';
 const data=(tab==='detail'?rows:items).filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(search.toLowerCase())));const heads=tab==='detail'?['Item ID','Product Id','SKU ID','Gross Units(total)','Projected unit']:['Item ID','Gross Units(total)','Projected unit'];page=Math.min(page,Math.max(0,Math.ceil(data.length/50)-1));
 $('rowCount').textContent=num(data.length)+' rows';$('table').innerHTML=data.length?`<table><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${data.slice(page*50,page*50+50).map(r=>`<tr>${heads.map(h=>`<td class="${typeof r[h]==='number'?'numeric':''}">${h==='Item ID'&&!r[h]?'<span class="unmapped">Unmapped</span>':typeof r[h]==='number'?num(r[h]):esc(r[h])}</td>`).join('')}</tr>`).join('')}</tbody></table>`:`<div class="empty"><svg viewBox="0 0 48 48" aria-hidden="true"><path d="M8 38V25h8v13M20 38V17h8v21M32 38V8h8v30"/></svg><h3>${search?'No matching rows':'Your next plan starts here'}</h3><p>${search?'Try another Item ID, Product ID or SKU.':'Upload your item master and sales report above.'}</p></div>`;
 $('pageInfo').textContent=data.length?`Showing ${page*50+1}–${Math.min(data.length,page*50+50)} of ${num(data.length)}`:'';$('prev').disabled=page===0;$('next').disabled=(page+1)*50>=data.length;
 if(missing.length){message(`${missing.length} Product ID(s) need a mapping: ${missing.slice(0,12).join(', ')}${missing.length>12?'…':''}. Update and re-upload your master to enable export.`,true);}
}
for(const kind of ['master','sales'])$(kind).addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;action(async()=>{const rows=validateRows(await readFile(file),kind);if(kind==='sales'){project(rows,master);sales=rows;salesName=file.name;}else{master=rows;masterName=file.name;}page=0;message(`${file.name} uploaded. ${num(rows.length)} rows validated.`);});e.target.value='';});
$('search').addEventListener('input',e=>{search=e.target.value;page=0;render();});for(const name of ['detail','items'])$(name).onclick=()=>{tab=name;page=0;for(const t of ['detail','items']){$(t).classList.toggle('selected',t===name);$(t).setAttribute('aria-pressed',String(t===name));}render();};$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};
$('download').onclick=()=>action(async()=>{const rows=project(sales,master);if(!rows.length||rows.some(r=>!r['Item ID']))throw Error('Map all Product IDs before exporting.');await exportReport(rows,itemTotals(rows));message('Report downloaded with Product detail and Item totals worksheets.');});
function renderAuth(){if(!cloud){$('auth').innerHTML='<span class="badge">Supabase setup included</span>';return;}$('connection').textContent=user?'Cloud connected':'Cloud available';$('cloudText').textContent=user?`Signed in as ${user.email}. Save before closing. Loading replaces the current session.`:'Sign in to save your master and sales data privately across devices.';
 $('auth').innerHTML=user?'<div class="cloud-actions"><button id="save">Save workspace</button><button id="load">Load saved</button><button id="out">Sign out</button></div>':'<form id="login"><label>Email<input type="email" id="email" required autocomplete="email"></label><label>Password<input type="password" id="password" required minlength="8" autocomplete="current-password"></label><button class="primary" type="submit">Sign in</button><button type="button" id="signup">Create account</button></form>';
 if(user){$('save').onclick=()=>action(async()=>{await saveWorkspace(user,{sales,master,salesName,masterName});message('Workspace saved.');});$('load').onclick=()=>action(async()=>{if((sales.length||master.length)&&!confirm('Replace the current uploads with your saved workspace?'))return;const d=await loadWorkspace(user);if(!d)throw Error('No saved workspace yet. Upload files and choose Save workspace.');const check=(rows,kind)=>rows.length?validateRows([Object.keys(rows[0]),...rows.map(r=>Object.keys(rows[0]).map(k=>r[k]))],kind):[];const s=check(d.sales,'sales'),m=check(d.master,'master');project(s,m);sales=s;master=m;salesName=d.salesName;masterName=d.masterName;message('Saved workspace loaded.');});$('out').onclick=()=>action(async()=>{if(!confirm('Sign out and clear this session? Save your workspace first if needed.'))return;const {error}=await cloud.auth.signOut();if(error)throw error;sales=[];master=[];salesName='';masterName='';message('Signed out.');});}else{const auth=async(signup)=>{const form=$('login');if(!form.reportValidity())return;await action(async()=>{const credentials={email:$('email').value,password:$('password').value};const {error}=signup?await cloud.auth.signUp(credentials):await cloud.auth.signInWithPassword(credentials);if(error)throw error;message(signup?'Account created. Check your email if confirmation is enabled.':'Signed in. Choose Load saved to retrieve your workspace.');});};$('login').onsubmit=e=>{e.preventDefault();auth(false);};$('signup').onclick=()=>auth(true);}}
if(cloud){cloud.auth.getSession().then(({data,error})=>{if(error)message(error.message,true);user=data.session?.user??null;renderAuth();});cloud.auth.onAuthStateChange((_event,session)=>{user=session?.user??null;renderAuth();});}renderAuth();render();
